version: 2.1

commands:
  install-goreleaser:
    steps:
      - run: go install github.com/goreleaser/goreleaser@latest

jobs:
  test:
    working_directory: ~/project/
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test ./...
  release:
    working_directory: ~/project/replay
    parameters:
      args:
        default: ""
        type: string
    docker:
      - image: cimg/go:1.23
    steps:
      - install-goreleaser
      - checkout
      - run:
          name: release
          command: goreleaser release << parameters.args >>

workflows:
  main:
    jobs:
      - test
      - release:
          name: test_release
          args: "--snapshot --clean"
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          context:
            - github
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
